# Generated by Django 4.1.3 on 2023-01-03 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(default='', max_length=255)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.\t\tUnselect this instead of deleting accounts.')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=250, null=True)),
                ('invoice', models.CharField(blank=True, max_length=355, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('total_amount_paid', models.CharField(blank=True, max_length=250, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=250, null=True)),
                ('balance_payable', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_policy', models.CharField(blank=True, max_length=250, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('payment_week', models.CharField(blank=True, max_length=250, null=True)),
                ('month_of_payment', models.CharField(blank=True, max_length=250, null=True)),
                ('year_of_payment', models.CharField(blank=True, max_length=250, null=True)),
                ('range_to_pay', models.CharField(blank=True, max_length=250, null=True)),
                ('days_overdue', models.CharField(blank=True, max_length=250, null=True)),
                ('overdue', models.CharField(blank=True, max_length=250, null=True)),
                ('business_name', models.CharField(blank=True, max_length=250, null=True)),
                ('month', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('out_of_time', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
