# Generated by Django 4.1.3 on 2023-01-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0002_providers_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='payment_term',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
