# Generated by Django 4.1.2 on 2022-12-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0002_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
    ]
