# Generated by Django 4.1.3 on 2023-01-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0002_bank_select_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='select_bank',
        ),
    ]
