# Generated by Django 4.1.3 on 2022-12-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0003_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='business_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='month',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='out_of_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
