# Generated by Django 4.1.3 on 2023-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0003_providers_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
