# Generated by Django 4.1.3 on 2023-01-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0004_providers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='siipassword',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='siiusername',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
