# Generated by Django 4.1.3 on 2023-01-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0007_alter_providers_days_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='week',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
