# Generated by Django 4.1.3 on 2023-01-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0011_alter_providers_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='add1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='add2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='add3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='add4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
