# Generated by Django 4.1.3 on 2023-01-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0014_amountpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountpaid',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
