# Generated by Django 4.1.3 on 2023-01-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0015_amountpaid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountpaid',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollapp.providers'),
        ),
    ]
