# Generated by Django 4.1.3 on 2023-02-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0017_providers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='week1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providers',
            name='week2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providers',
            name='week3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providers',
            name='week4',
            field=models.BooleanField(default=False),
        ),
    ]
