# Generated by Django 4.1.3 on 2023-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0018_providers_week1_providers_week2_providers_week3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='insert_status',
            field=models.BooleanField(default=False),
        ),
    ]
