# Generated by Django 4.1.3 on 2023-02-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0019_providers_insert_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='startdate',
        ),
        migrations.AddField(
            model_name='user',
            name='month_of_payment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_payment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
