# Generated by Django 4.1.3 on 2023-02-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0020_remove_user_enddate_remove_user_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='month_of_payment',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='year_of_payment',
            new_name='year',
        ),
    ]
