# Generated by Django 4.1.3 on 2023-02-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0021_rename_month_of_payment_user_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='csv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
