# Generated by Django 4.1.3 on 2023-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0022_providers_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='providers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
