# Generated by Django 4.1.3 on 2023-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollapp', '0023_providers_created_at_providers_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='providers',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
